apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-tp2.fullname" . }}-helm
  labels:
    app: {{ include "app-tp2.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-tp2.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-tp2.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
