apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-tp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-tp2
  template:
    metadata:
      labels:
        app: app-tp2
    spec:
      containers:
        - name: app-tp2
          image: nbhf/application-tp2:latest
          ports:
            - containerPort: 8080
